### ISSUE TITLE
Plugin only shows [object Promise]

### ISSUE THREAD

**Issue by eriksteinebach** [ludoviclefevre/hexo-helper-seo-structured-data#1]
When I add this plugin to my site, the only thing that happens is that [object Promise] appears at the top of my page, instead of the information:
![capture](https://cloud.githubusercontent.com/assets/5765891/17527537/5b1f21f6-5e31-11e6-80e0-d2618caf6259.JPG)
Instead of the structured data, only [object Promise] is outputted in the source. 
What am I doing wrong?

**Comment by ludoviclefevre** [comment]
Hi,

It's fixed in v0.0.3.

Thx

**Comment by eriksteinebach** [comment]
Yes, now it works as expected. Thank you!
